version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=Peter.Mikkelsen
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=demodatabase

  jaeger:
    image: "jaegertracing/all-in-one"
    ports:
      - "16686:16686"
      - "14250"
      - "4317:4317"