ktor:
  application:
    modules:
      - com.demo.ApplicationKt.module
  deployment:
    port: 8080

storage:
  jdbcURL: "jdbc:postgresql://localhost:5432/demodatabase"
  user: "Peter.Mikkelsen"
  driverClassName: org.postgresql.Driver
